version: '2.1'
services:
  ecom_vue:
    image: ecom_vue_image
    restart: always
    ports:
      - 80:80
    build:
      context: ./ecommerce
      dockerfile: ./Dockerfile

  ecom_golang:
    image: ecom_golang_v1
    logging:
      options:
        max-size: '50m'
        max-file: '5'
      driver: json-file
    restart: always
    ports:
      - 8000:8000
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: sh -c '/wait && ./ecom_golang'
    volumes:
      - ./logs:/app/src/logs
      - ./resources:/app/resources
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    logging:
      options:
        max-size: '50m'
        max-file: '5'
      driver: json-file
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_PASSWORD=heverlEE